### ISSUE TITLE
The key hash is not the same as the one I can generate

### ISSUE THREAD

**Issue by jedelacarrera** [clemdesign/ionic-3-facebook-login-sample#1]
When I generate the key hash and I add it to facebook developers site, the key does not match with the one that the app has. I tried changing the APP_NAME and the APP_ID, but it didn't work.

**Comment by clemdesign** [comment]
Maybe because your app is not signed with the Android debug Keystore.

In this case, you shall get the  SHA-256 signature of your App and convert it in base64 for Facebook APP.
